# project liquid biopsies 

Between May and June, 2022, I wrote R-code for the Princess Máxima Center within a project called "liquid biopsies". I worked on this project together with 2 other students: Pedro de Bos and Thijmen van Brenk. On this page, I will provide:

- a theoretical back ground, to highlight the importance of the project "liquid biopsies"
- back ground information to what we tried to achieve in our R project 
- a brief summary what the end product of our R project was 

## theoretical background 
Neuroblastoma is an embryonic malignancy that affects normal development of the adrenal medulla and para vertebral sympathetic ganglia in early childhood. Despite extensive studies to the molecular characteristics of human neuroblastomas, the initiation mechanisms and even its origin are still largely unknown. @marisRecentAdvancesNeuroblastoma2010

However, neuroblastoma is the most common extracranial solid tumor in children. Further more, it has high recurrence rates and low survival rates. Therefore, early diagnosis, treatment response evaluation, and recurrence monitoring are of great significance for NB patients. @YeTiHuoJianZaiShenJingMuXiBaoLiuZhongDeLinChuangYanJiuJinZhan2022

A further complication is that neuroblastoma exhibits genetic, morphological and clinical heterogeneity. This in term limits the efficacy of existing treatment. Therefor, Gaining detailed knowledge of the molecular signatures and genetic variations involved in the pathogenesis of neuroblastoma is necessary to develop safer and more effective treatments for neuroblastomas. @zafarMolecularTargetingTherapies2021 

The wide genetic variation, also means that several different kinds of cell progresses can be effected. These include changes in the regulatory role in differentiation, apoptosis, cell proliferation, tumourigenesis, angiogenesis or metastasis of neuroblastoma. The mutations in different cell progresses may require different treatments, which can further complicate treatment when the genetic variation of the tumor cells is not well understood,  @aygunBiologicalGeneticFeatures2018

The issues with neuroblastoma is that to properly monitor the progression of the tumor, samples need to be taken often. And tumor biopsies can be very invasive. This may lead to damage from the tumor biopsies, or to a lack of sampling which limits the effectiveness of the treatment. A possible solution, lays with liquid biopsies. Liquid biopsies, is a method of obtaining genomic material of tumors from  blood samples. tumors secret DNA to the blood, which is called cell free DNA. This cell free DNA  can be amplified, sequences and analysed. A study has shown that the proportion of tumor-derived DNA in cell free DNA was 42.5% (16.9%-55.9% across all samples). This could potentially mean sufficient sensitivity of liquid biopsy for neuroblastoma.@shiraiQuantitativeAssessmentCopy2022

## R project 

At this moment, data sets of DNA from tumor biopsies and liquid biopsies of patients with neuoblastoma are compared manual at the Princes Maxima Center. This is very time consuming, and when working with time pressure from an increasing number of patients, can lead to human error. And within the view of "open science", this method is not reproducible or robust. In our R project, we set out to solve this issue using the R-package called "shinny". We used this package to build an interactive web database, which: 

- automates the process of aligning DNA sets of samples 
- allows for easy comparing and visualization of sequencing results
- introduces a reproducible and tidy work environment 
- gives the possibility to easily save and share files 
- requires a very limited amount of R-knowledge to set up (and comes with a manual)

Our working partner at the princess Máxima Center was very satisfied with the end product we delivered. Though, because of an agreement of secrecy, I am not allowed to share any more details about this end product. 


